### ISSUE TITLE
Improve the parser

### ISSUE THREAD

**Issue by j-jzk** [j-jzk/klang#23]
Now that the base of the parser is more or less done, more concrete points should be addressed:
- [x] Work out what will be stored in the AST nodes and how will they be identified and reduced (#27)
- [x] Generalize the parser and its builder to work with node IDs and types supplied by the user (#27)
- [x] #28
    - [x] #30 
- [ ] ~~Better test suite~~ - #29 

and other, smaller improvements (the TODOs in the code).
