### ISSUE TITLE
Add additional functionality to the lexer

### ISSUE THREAD

**Issue by j-jzk** [j-jzk/klang#4]
- [x] Add the ability to ignore tokens (for example comments or whitespace) - #7
- [x] Throw an error when an unexpected character is encountered - #8
    - ~This could be done by passing a `.` regex internally to klang-re and seeing if it was matched~ - I've solved it differently in the end
- [x] Store positions of the tokens - #17
    - This would maybe require creating a new class, which would store some sort of identifier of the input source (for example the filename)
